###Boolean Operation

Is ```np.dot(boolean , boolean)``` same as ```np.dot(int , int)``` ?


In this case, which type would be suitable for calculating likelihoods?
* In numpy, operations such as dot product or sum of two boolean arrays do not produce integer arrays.

In [1]:
import numpy as np

a=np.array([0,1,0,1,0])
b=np.array([1,1,0,1,1])

dot_int=np.dot(a.astype(int),b.astype(int))
dot_bool=np.dot(a.astype(bool),b.astype(bool))

sum_int=a.astype(int)+b.astype(int)
sum_bool=a.astype(bool)+b.astype(bool)

print("dot_int:\n",dot_int)
print("dot_bool:\n",dot_bool)

print("sum_int:\n",sum_int)
print("sum_bool:\n",sum_bool)

# logic operation(same as sum_bool)
# sum operation with two boolean arrays is regarded as logic operation
print("logic operation:",a.astype(bool) | b.astype(bool))

dot_int:
 2
dot_bool:
 True
sum_int:
 [1 2 0 2 1]
sum_bool:
 [ True  True False  True  True]
logic operation: [ True  True False  True  True]


###np.astype()

In [ ]:
x=np.array([1,2,2.5])

# original data type
print(x.dtype)

# converted data type
print(x.astype(int))

original data type
float64
[1 2 2]


###Finding Elements
[reference(boolean indexing)](https://python-course.eu/numerical-programming/numpy-boolean-indexing.php)

In [ ]:
count_a_b=a==b # find the same value and return boolean index
print(count_a_b)

print(np.sum(count_a_b)) # sum of boolean index = number of Trues

[False  True  True  True False]
3


###np.amax()

In [ ]:
a=np.arange(4).reshape((2,2))
print(a)

print(np.amax(a)) # max value
print(np.amax(a, axis=0)) # max value among the same columns
print(np.amax(a, axis=1)) # max value among the same rows

[[0 1]
 [2 3]]
3
[2 3]
[1 3]


###np.argmax()

In [ ]:
a=np.arange(6).reshape(2,3)+10
print(a)

print(np.argmax(a)) # index of max value
print(np.argmax(a, axis=0)) # index of max value among the same columns
print(np.argmax(a,axis=1)) # index of max value among the same rows 

[[10 11 12]
 [13 14 15]]
5
[1 1 1]
[2 2]


###sklearn.preprocessing.LabelEncoder()

In [ ]:
#generate labels for the strings
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
print(le.fit_transform(["paris","amsterdam","new york"]))

[2 0 1]


###np.expand_dims()

In [ ]:
a=np.array([1,2,3,4])
print(a)
print(a.shape) #original shape

print("-------\n")
b=np.expand_dims(a,axis=0)
print(b)
print(b.shape) #expanded shape(axis=0)

print("-------\n")
c=np.expand_dims(a, axis=1)
print(c)
print(c.shape) #expanded shape(axis=1)

[1 2 3 4]
(4,)
-------

[[1 2 3 4]]
(1, 4)
-------

[[1]
 [2]
 [3]
 [4]]
(4, 1)


###np.squeez()

In [ ]:
x=np.array([[[0],[1],[2]]])
print(x)
print(x.shape) #original shape

print("---------\n") 
print(np.squeeze(x))
print(np.squeeze(x).shape) #squeezed shape

print("---------\n")
print(np.squeeze(x,axis=0).shape)  #squeezed shape(axis=0)
#print(np.squeeze(x, axis=1).shape) #error!
print(np.squeeze(x,axis=2).shape) #squeezed shape(axis=2)

[[[0]
  [1]
  [2]]]
(1, 3, 1)
---------

[0 1 2]
(3,)
---------

(3, 1)
(1, 3)


###np.argsort()

In [8]:
x=np.array([[0,3],[2,2]])

ind1=np.argsort(x, axis=0)
ind2=np.argsort(x,axis=1)

print("original x\n",x)
print("--------------")

print("Indices of values sorted by axis=0 in numerical order\n",ind1)
print("--------------")

print("Indices of values sorted by axis=1 in numerical order\n",ind2)
print("--------------")



#np.take_along_axis() returns sorted values
print(np.take_along_axis(x,ind1,axis=0))
print("--------------")
print(np.take_along_axis(x,ind2,axis=0))

original x
 [[0 3]
 [2 2]]
--------------
Indices of values sorted by axis=0 in numerical order
 [[0 1]
 [1 0]]
--------------
Indices of values sorted by axis=1 in numerical order
 [[0 1]
 [0 1]]
--------------
[[0 2]
 [2 3]]
--------------
[[0 2]
 [0 2]]


###np.take()

In [ ]:
a=[4,3,5,7,6,8]
indices=[0,1,4]

print(np.take(a,indices))

print(np.take(a,[[0,1],[2,3]]))

[4 3 6]
[[4 3]
 [5 7]]


###scipy.stats.mode()

In [13]:
from scipy import stats

a=np.array([[3,0,3,7],
           [3,2,6,2],
           [1,7,2,8],
           [3,0,6,1],
           [3,2,5,5]])
print(a)

stats.mode(a, keepdims=True) #returns the most common value in each column

[[3 0 3 7]
 [3 2 6 2]
 [1 7 2 8]
 [3 0 6 1]
 [3 2 5 5]]


ModeResult(mode=array([[3, 0, 6, 1]]), count=array([[4, 2, 2, 1]]))

###np.array_split()

In [ ]:
x=np.arange(8.0)

np.array_split(x,3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

###np.diagonal()

In [ ]:
#extract specific diagonal
a=np.arange(9).reshape(3,3)
print(a)
print(a.diagonal())


#create diagonal matrix
b=np.zeros([3,3])
np.fill_diagonal(b,val=[1,2,3])
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


###np.unravel_index

In [12]:
#In our example, unravel=np.unravel_index(index,shape)
unravel=np.unravel_index([22,41,37],(7,6))
print(unravel)

print("\n------------------------")
print("How does unravel_index() work? Below is just an example to explain the algorithm\n")

print("First, flatten the matrix. Note that [22,41,37] is indices.\n")
print(np.arange(np.amax([22,41,37])+1))


print("\nSecond, reshape the matrix to (7,6)")
print(np.arange(np.amax([22,41,37])+1).reshape(7,6))


print("\nThrid, find the index of [22,41,37] in the reshaped matrix")
print("\nThe indices of 22, 41, and 37 are (3,4), (6,5), (6,1) respectively, which matches to the result of unravel\n(first array: axis=0, second array: axis=1")

(array([3, 6, 6]), array([4, 5, 1]))

------------------------
How does unravel_index() work? Below is just an example to explain the algorithm

First, flatten the matrix. Note that [22,41,37] is indices.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]

Second, reshape the matrix to (7,6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]]

Thrid, find the index of [22,41,37] in the reshaped matrix

The indices of 22, 41, and 37 are (3,4), (6,5), (6,1) respectively, which matches to the result of unravel
(first array: axis=0, second array: axis=1
